# Generated by Django 2.1 on 2019-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('qualifications', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
